### ISSUE TITLE
Taller de Flutter

### ISSUE THREAD

**Issue by joseangel092004** [ISCOUTB/DG-DreamTrip#20]
Hacer el tutorial de flutter

**Comment by joseangel092004** [comment]
Después de ver tutoriales acerca de Flutter, puedo concluir que Flutter es un framework de UI (Interfaz de Usuario) de código abierto que permite desarrollar aplicaciones móviles nativas para iOS y Android desde una única base de código utilizando el lenguaje Dart. Es conocido por su enfoque en el rendimiento y la flexibilidad en el diseño, gracias a su motor de renderizado propio y un rico conjunto de widgets personalizables. Lo que aprendí de Flutter es que ofrece un flujo de trabajo eficiente para construir interfaces de usuario elegantes y rápidas, facilitando la creación de aplicaciones multiplataforma con una apariencia y rendimiento nativo, mientras aprovechas una comunidad activa y una amplia documentación.

**Comment by joseangel092004** [comment]
Flutter en visual studio code (vscode)

![Image](https://github.com/user-attachments/assets/561d671b-6122-4d53-99d5-3a72327b3234)

**Comment by joseangel092004** [comment]
Configuración de proyecto App Web en FutterFlow

![Image](https://github.com/user-attachments/assets/619d7a7b-703d-4db9-84ab-9025948c9708)

**Comment by jairoserrano** [comment]
adelant

**Comment by Angelsistemas7** [comment]
flutter instalado igualmente

![Image](https://github.com/user-attachments/assets/2aa4b296-0d44-4bed-9e1a-8ed0fd9e358c)
