### ISSUE TITLE
Diseño básico del Backend

### ISSUE THREAD

**Issue by joseangel092004** [ISCOUTB/DG-DreamTrip#21]
Definir el uso de Flastapi o Flask y por qué?

**Comment by joseangel092004** [comment]
Para el desarrollo del backend de nuestro proyecto de DreamTrip, haremos el uso de **FastAPI** debido a su alto rendimiento y capacidad para manejar solicitudes concurrentes, lo cual es crucial para funciones intensivas en IN/OUT como la integración con APIs de proveedores de vuelos y el motor de recomendaciones basado en algoritmos de aprendizaje automático. Además, FastAPI ofrece validación automática de datos y generación de documentación interactiva, lo que facilitará el desarrollo rápido y seguro de funcionalidades como el registro y autenticación de usuarios, perfiles personalizables, creación y edición de itinerarios, y el foro comunitario. Esto lo hace ideal para un proyecto con múltiples componentes interactivos y requisitos de alta eficiencia y escalabilidad como el de nuestro proyecto DreamTrip.

**Comment by joseangel092004** [comment]
![Image](https://github.com/user-attachments/assets/4321d174-99cc-4933-b2e0-b07f8cdf982e)
![Image](https://github.com/user-attachments/assets/8e960851-cf8e-46f3-8935-5f0ebf7a3ddf)
![Image](https://github.com/user-attachments/assets/d92a61cd-8ca6-4d58-af61-e6d0577d9f22)
![Image](https://github.com/user-attachments/assets/5650e8e1-ca14-4328-8a6c-2095d776275e)
![Image](https://github.com/user-attachments/assets/528b0f6a-ac6f-476b-9e57-8cc974f7b848)

**Comment by joseangel092004** [comment]
![Image](https://github.com/user-attachments/assets/ff9a0278-6d1d-4a24-abcd-c10c96f2bcd8)

**Comment by jairoserrano** [comment]
adelante

**Comment by Angelsistemas7** [comment]
por otro lado, estoy usando esta api que es un poco mas flexible en cuanto a su uso gratuito para ir comenzando con los servicios que necesitaremos para nuestro codigo.

![Image](https://github.com/user-attachments/assets/fa4c744a-dcab-4294-b029-ceb935e82f55)

primero tenemos nuestro token para llamar a la api 

![Image](https://github.com/user-attachments/assets/a583fc64-94e1-4b58-90d9-55ddd32c4e05)
