### ISSUE TITLE
Definir Wireframes de toda la aplicación

### ISSUE THREAD

**Issue by joseangel092004** [ISCOUTB/DG-DreamTrip#22]

**Comment by joseangel092004** [comment]
**1. Pantalla de Inicio (Home)**
   - Barra de navegación superior: Logo, menú, perfil.
   - Banner principal: Promociones o características destacadas.
   - Búsqueda: Campo de búsqueda de destinos.
   - Categorías de viaje: Ofertas, destinos populares, temas (aventura, relax, etc.).
   
   **2. Pantalla de Búsqueda de Destinos**
   - Barra de búsqueda: Campo para ingresar destino, fechas, tipo de viaje.
   - Filtros: Ubicación, precio, tipo de alojamiento, etc.
   - Resultados: Listado de destinos con imágenes, precios y valoraciones.

     **3. Pantalla de Detalle de Destino**
   - Imágenes: Galería del destino.
   - Descripción: Información detallada del destino.
   - Opciones de viaje: Paquetes, actividades.
   - Reseñas: Opiniones de otros usuarios.
   - Botón de Reserva: Llamado a la acción para reservar.

      **4. Pantalla de Reserva**
   - Detalles del viaje: Fechas, número de personas, tipo de habitación.
   - Opciones adicionales: Actividades extras, seguros.
   - Resumen del costo: Detalle del precio total.
   - Formulario de pago: Información de tarjeta, dirección de facturación.

      5. **Pantalla de Perfil de Usuario**
   - Información personal: Nombre, correo, foto de perfil.
   - Historial de reservas: Viajes anteriores, detalles.
   - Configuración: Preferencias, ajustes de cuenta.
   - Soporte: Contacto y ayuda.

       6. **Pantalla de Confirmación de Reserva**
   - Detalles de la reserva: Información del viaje, fechas, precio.
   - Código de confirmación: Número de reserva.
   - Opción para compartir: Enviar detalles por correo o redes sociales.
 
       **7. Pantalla de Notificaciones**   
   - Alertas: Actualizaciones sobre reservas, ofertas especiales.
   - Mensajes importantes: Recordatorios de viaje, cambios en la reserva.

**Comment by joseangel092004** [comment]
Diseño de nuestro wireframe: https://www.figma.com/design/7ORqB7UUdMrZJtW4yrGOow/Dise%C3%B1o-aplicaci%C3%B3n-web?node-id=0-1&t=osl49YimRqelLsqc-1

**Comment by andresgv09** [comment]
![Image](https://github.com/user-attachments/assets/c7369a04-735d-4d0c-9a5c-a2f4b8bf6f96)

**Comment by joseangel092004** [comment]
![Image](https://github.com/user-attachments/assets/1f2d301f-22e9-4ed7-a92e-b63b51617995)
